name: Build and Deploy Angular
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Execute build and tests
        run: |
          npm install --quiet
          npm run build
          
      - name: Zip Build
        uses: TheDoctor0/zip-release@v0.2.1
        with:
          filename: release.zip
          path: dist
          
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v4
        with:          
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          region: sa-east-1
          application_name: logstore         
          environment_name: Logstore-env-1
          deployment_package: release.zip

