name: Build and Deploy Angular
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Execute build and tests
        run: |
          npm install --quiet
          npm run build
          
      - name: Zip Build
        uses: TheDoctor0/zip-release@v0.2.1
        with:
          # Filename for archive
          filename: release.zip
          # Base path for archive files
          path: dist          
          
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v4
        with:
          # AWS Access Key
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS Secret Key
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          # AWS Region
          region: sa-east-1
          # Beanstalk application name
          application_name: logstore         
          # Zip file with the version to deploy. If skipped the action will deploy existing version.
          deployment_package: release.zip

